export const GET_CUSTOMERS_READINGS = 'GET_CUSTOMERS_READINGS'
export const GET_CUSTOMERS_READINGS_ERROR = 'GET_CUSTOMERS_READINGS_ERROR'
export const GET_CURRENT_CUSTOMER = 'GET_CURRENT_CUSTOMER'
export const GET_CURRENT_CUSTOMER_LOADING = 'GET_CURRENT_CUSTOMER_LOADING'
export const GET_CURRENT_CUSTOMER_STOP_LOADING =
  'GET_CURRENT_CUSTOMER_STOP_LOADING'
